name: Makefile CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: start
      run: start
    - name: make test
      run: test
    - name: make lint
      run: lint
