name: Makefile CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: make install
    - name: make test
      run: test
    - name: make lint
      run: lint

